name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create file list
        id: files_list
        run: mkdir output  # create output dir
      - uses: docker://pandoc/latex:2.9
        with:
          args: -v "/home/runner/work/HydDown/HydDown":"/github/workspace" --resource-path=.:docs --resource-path=.:docs/img --toc  --top-level-division=chapter  --number-sections --listings --output=output/Test.pdf  Test.md
          #-v "/home/runner/work/HydDown/HydDown":"/github/workspace" --toc --filter pandoc-crossref --citeproc --bibliography=references.bib --top-level-division=chapter --resource-path=.:/home/runner/work/HydDown/HydDown/docs --data-dir=templates --number-sections --listings
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
