name: Manual

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd docs/
      - uses: docker://pandoc/core
        with:
          args: >-  # allows you to break string into multiple lines
            --toc
            --filter pandoc-crossref 
            --filter pandoc-citeproc 
            --bibliography=references.bib 
            --top-level-division=chapter 
            --number-sections 
            --output=output/MANUAL.pdf 
            --listings
            MANUAL.md 
            
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
