name: Manual

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: | 
          cd docs
          mkdir output
      - uses: docker://pandoc/core
        with:
          args: "--toc --filter pandoc-crossref --citeproc --bibliography=references.bib --top-level-division=chapter --number-sections --output=output/MANUAL.pdf --listings MANUAL.md"
      - uses: actions/upload-artifact@main
        with:
          name: output
          path: output
     
